---
version: '3.4'
services:
  ${acs.host}:
    image: acs-send-mail:development
    build:
      dockerfile: ./Dockerfile
      context: ../../send-mail-platform-docker/target
    volumes:
      - send-mail-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - ${db.host}
    networks:
      - backend

  ${share.host}:
    image: share-send-mail:development
    build:
      dockerfile: ./Dockerfile
      context: ../../send-mail-share-docker/target
    environment:
      REPO_HOST: ${acs.host}
      REPO_PORT: 8080
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${pristy.host}:
    image: send-mail-aca:development
    build:
      dockerfile: ./Dockerfile
      context: ../../send-mail-aca-docker/target
      args:
        TOKEN_API: ${TOKEN_API}
        GITLAB_API: ${GITLAB_API}
    environment:
      BASE_PATH: ./
      PORT: 8080
      ACS_URL: http://${public.host}:${public.port}

      URL_HOST_ADF: http://${public.host}:8080/alfresco
      APP_BASE_SHARE_URL: http://${public.host}:8080/share/s
      PROXY_HOST_ADF: http://${public.host}:8080/demo
      URL_HOST_BPM_ADF: http://${public.host}:8080
      NOTIFICATION_LAST: 2000
      AUTH_TYPE: BASIC
      PROVIDERS: ALL
    ports:
      - "${public.port}:8080"
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${db.host}:
    image: ${docker.postgres.image}:${docker.postgres.version}
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - send-mail-db-volume:/var/lib/postgresql/data
    networks:
      - backend

  ${solr.host}:
    image: ${docker.solr.image}:${docker.solr.version}
    environment:
      SOLR_ALFRESCO_HOST: ${acs.host}
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ${solr.host}
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    volumes:
      - send-mail-contentstore-ass-volume:/opt/alfresco-search-services/contentstore
      - send-mail-data-ass-volume:/opt/alfresco-search-services/data
    networks:
      - backend

volumes:
  send-mail-acs-volume:
  send-mail-db-volume:
  send-mail-contentstore-ass-volume:
  send-mail-data-ass-volume:

networks:
  backend:
